name: Java CI with Maven
run-name: ${{ github.actor }} is building a java application
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check the workspace
        run: ls -la ${{ github.workspace }}
      - name: Install Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'
      - name: Check Java and Maven Versions
        run: |
          java -version
          mvn --version
      - name: Run the tests
        run: mvn test
      - name: Package the application
        run: mvn package
      - name: Test the jar file
        run: java -jar ${{ github.workspace }}/target/gs-maven-0.1.0.jar
