name: Java CI with Maven
run-name: ${{ github.actor }} is building a java application
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Java and Maven Versions
        run: |
          java -version
          mvn --version
